### ISSUE TITLE
Request : Guild Achievements Spam Disable

### ISSUE THREAD

**Issue by WingZeroMaster** [ls-/ls_Toasts#68] opened 2024-09-06 05:48 UTC
Request : Guild Achievements Spam Disable
I wish there was a way to disable guild achievements spam. because  Blizzard's guild achievement notifications spam bug.....

**Comment by Taizunz** [comment] 2024-09-07 10:22
I requested a very similar thing back in April
https://github.com/ls-/ls_Toasts/issues/59

**Comment by ls-** [comment] 2024-09-11 05:36
I need some help from either of you since I'm not sure how this stuff works, it's been a while since I was in any guild, so I've never experienced this bug first hand. When a toast for a buggy guild achievement pops up, how does it look? Like, do you see the number of points? Is the border yellow? Or it's just blank with a grey border like a proper toast for repeated achievements?

**Comment by WingZeroMaster** [comment] 2024-09-11 08:27
![WoWScrnShot_091124_012916](https://github.com/user-attachments/assets/adb974ce-fc2a-48c3-8a48-56901a6818ab)

(Sorry for the Google Translate....)
Being healthy is the most important!!! :)
The screenshot below is the screen when the guild achievement bug occurs.
In addition, the addons below are said to be addons to block the bug.
I think it would be good to refer to them.
thank you for nice addon.
https://www.curseforge.com/wow/addons/guildachievementblocker
https://www.curseforge.com/wow/addons/disableguildachievements

**Comment by ls-** [comment] 2024-09-11 08:38
I checked all those addons to get the answer, but most of them either don't work or don't answer the question 😂 Can't open the screenshot, but the thumbnail was good enough to see that what the addon sees is basically a brand new achievement and not a repeat 😅 

Anyway, I'm currently testing two toggles to suppress repeats for character and guild achievements, I don't think account achievements can generate repeats 🤔 

![image](https://github.com/user-attachments/assets/bebb032e-bd13-4a0a-be93-81acb5894ad0)

Hopefully, this will fix the issue.

**Comment by ls-** [comment] 2024-09-11 10:23
Fixed, it'll be released with the next update, but not today.

**Closed by ls-** 2024-09-11 10:23 UTC

**Comment by ls-** [comment] 2024-09-25 18:33
The previous workaround only worked under very specific circumstances, so I had to rework it. I even joined a guild where people were regularly experiencing the bug so I could investigate the cause properly.

With the next update I'll be adding an optional filter for guild achievements, unfortunately, there's no way to reliably automate it without affected people in newer guilds who might want to see these achievements.

![image](https://github.com/user-attachments/assets/c5a9bbef-a005-4700-b23e-672df131e839)
