### ISSUE TITLE
wlk bug 

### ISSUE THREAD

**Issue by shenhix** [ls-/ls_Toasts#44] opened 2022-09-26 11:20 UTC
The wlk version will cause the Blizzard native prompt box to disappear!
Cancelling the achievement prompt cannot be restored, it can only be disabled!

**Comment by ls-** [comment] 2022-09-27 06:59
It's not a bug, it's an intended behaviour. The addon completely replaces the default toasts system, so when you disable the addon just stops showing toasts of that particular type, it won't re-enable Blizz toasts of that kind. It's done for multiple reasons, but the gist of it is that it's just due to how Blizz write their stuff, it can be hard or even impossible to re-enable certain types of toasts without messing up everything else.

**Comment by Velarax** [comment] 2022-10-23 00:38
As of 10/22/22 cannot get the interface by typing either /lst or /lstoasts;  either returns a message:  Type '/help' for a listing of a few commands.

**Comment by s890214** [comment] 2022-10-24 09:50
yes，your achievement toasts not cool，default alert system is better，but only  achievement toasts,

**Comment by ls-** [comment] 2022-10-24 18:05
@Velarax I'll check it out, thanks. I don't play wotlk classic, so I wasn't aware...

**Comment by Velarax** [comment] 2022-10-24 18:25
Thank you very much :D

**Comment by ls-** [comment] 2022-10-24 18:30
@Velarax any errors? Does the addon work? Is it even loaded? If it tells you that you need to try /help for the list of commands, it means that my addon basically failed to load for whatever reason. Did you try deleting its settings from the WTF folder? They're in `WTF/Account/YourAccName/SavedVariables`, delete both `ls_Toasts.lua` and `ls_Toasts.lua.bak`.

**Comment by ls-** [comment] 2022-10-24 18:32
@s890214 I'm not mixing my toasts with the default ones, it's a recipe for disaster. Is there anything in particular you don't like about my achievement toasts?

**Comment by Velarax** [comment] 2022-10-24 19:08
Although the addon apparently is checked for loading, it is not functioning at all.  I already deleted both the cache and the .lua and .lua.bak files.

Typing /lstoasts gets the standard /help? message, so apparently it isn't loading.  I have tried disabling other addons to see if there is any conflict, but that doesn't appear to be the case.

**Comment by ls-** [comment] 2022-10-24 19:19
Try `/dump IsAddOnLoaded("ls_Toasts")`, it should return 2 `true`s.

**Comment by Velarax** [comment] 2022-10-24 19:41
DOH!  That was it, I feel stupid.  Thanks.

**Comment by ls-** [comment] 2022-10-24 20:47
@Velarax ahahah, it happens, can't fault you, it's like the 3-5 time I run into this issue. Do you by any chance use wowup? and where from do you download it? wago? cf? wowi?

**Comment by Velarax** [comment] 2022-10-24 21:01
Actually curse is the culprit.  I manually updated the one they had uploaded as "wrath."  I see it's been fixed now.

**Comment by s890214** [comment] 2022-10-25 01:42
> @s890214 I'm not mixing my toasts with the default ones, it's a recipe for disaster. Is there anything in particular you don't like about my achievement toasts?

your achievement toasts is too ordinary.
It should be different from the toasts, Such as size and time
It's not easy to detect right now，
Because it's just like any other

![db98e1832e2e2a9989d6703bbb6c8e82](https://user-images.githubusercontent.com/29193110/197661504-3772c8a6-a74b-4ce6-8d87-20c65a4cede8.jpeg)

**Comment by ls-** [comment] 2022-10-25 09:00
I'll look into making it more ornate, prob an extra overlay a la the dragon for legendaries. But I'll do that only after I'm done dealing with the income sh*tshow that's the DF prepatch release XD

**Comment by ls-** [comment] 2022-11-02 14:59
Old:
![image](https://user-images.githubusercontent.com/2725970/199520909-d9707bcd-7898-44db-8b4a-0f08a939f4dc.png)
![image](https://user-images.githubusercontent.com/2725970/199521915-897f63bc-2d22-4339-a575-287e6c29f343.png)

New:
![image](https://user-images.githubusercontent.com/2725970/199521753-64207832-8bbd-432b-abda-af82252fe87b.png)
![image](https://user-images.githubusercontent.com/2725970/199521779-3e3d056f-9d0b-4ad7-a49d-8df17959daa3.png)

This is my attempt to make my achievement toasts a bit fancier.

**Closed** 2022-11-02 15:01 UTC
